In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data_nse = pd.read_excel('NSE.xlsx')
data_nifty50 = pd.read_excel('NIFTY_50.xlsx')
data_bnifty = pd.read_excel('NIFTY_BANK.xlsx')

In [3]:
df = pd.concat([data_nse, data_nifty50, data_bnifty], axis=0)

In [4]:
df.reset_index(drop=True, inplace=True)

In [5]:
df = df.drop_duplicates(subset=['TIC'])
df.reset_index(drop=True, inplace=True)

In [6]:
df

,TIC,Latest Price,Score,PE Ratio,Dividend,SMA_20,SMA_50,52_Week_Low,52_Week_High,Annual Volatility,Sharpe Ratio,MaxDD,CVaR,VaR
0,KERNEX.NS,371.750000,100,NaN,1.00,356.914996,315.290997,76.10,389.90,0.514450,3.89,-0.301682,0.049764,0.049069
1,NDTV.NS,357.850006,100,25.25,0.80,332.205000,384.959999,75.00,573.00,0.818738,2.82,-0.428327,0.070114,0.049950
2,ROHLTD.NS,267.600006,99,NaN,2.00,273.532503,269.282001,78.80,307.90,0.541322,2.41,-0.232167,0.058249,0.048598
3,ADANIENT.NS,4008.850098,98,587.89,1.00,3501.565002,3479.865010,1528.80,4048.95,0.373013,2.39,-0.177788,0.052684,0.034634
4,OILCOUNTUB.NS,22.950001,99,1.01,2.00,20.902500,15.983000,7.30,25.65,0.528420,2.22,-0.358974,0.049264,0.047142
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
515,COALINDIA.NS,253.250000,93,5.97,3.00,243.805000,234.082000,139.15,263.40,0.351835,1.48,-0.192605,0.046943,0.032675
516,NESTLEIND.NS,20322.500000,86,90.50,120.00,19993.376563,19326.864570,16000.00,21050.00,0.199398,0.20,-0.185800,0.027574,0.021461
517,HDFCLIFE.NS,542.650024,10,74.95,1.70,534.902502,544.281000,497.05,723.95,0.288025,-0.57,-0.294423,0.041799,0.029483
518,IDFCFIRSTB.NS,57.549999,58,21.97,0.75,56.547500,52.985000,28.95,59.45,0.392747,0.22,-0.440499,0.048627,0.033630
519,BANDHANBNK.NS,226.350006,17,9.28,1.00,251.122503,267.983999,220.05,349.55,0.414033,-0.46,-0.349876,0.068786,0.041728

In [7]:
df.sort_values(['Sharpe Ratio', 'Annual Volatility'], ascending=[False, True], inplace=True)

In [18]:
new_data = df[(df['Sharpe Ratio'] > 1.2) & (df['Annual Volatility'] < 0.52) & (df['MaxDD'] > -0.32) & (df['Latest Price'] <= 600)]

In [20]:
new_data.to_excel('Nov_Invest.xlsx', index=False)